pipeline { 
    agent any
    
    tools{
    	maven 'maven 3.9.8'
    }
    stages{ 
        stage('build'){ 
            steps{ 
                echo 'Compiling worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            steps{ 
                echo 'Running unit tests on worker app' 
            
            } 
        } 
        stage('package'){ 
            steps{ 
                echo 'packaging worker app'
                
                } 
            } 
        } 
    }
    post{ 
        always{ 
            echo 'Building multi-branch pipeline for worker is completed..' 

    }
  }
}
